name: checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  validate-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: ringo-org/github-actions-common/actions/change-file@main
      - uses: ringo-org/github-actions-common/actions/validate-assets@main
        with:
          max-image-size-mb: 5
          max-image-dimension: 2048
          require-meta: true
          pattern: "assets/**/*"
          require-power-of-two: true
