name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Run code quality action
        uses: ringo-org/test-action@main
